keystores (#32)
* Upgraded to scala 2.12.3

* Added authorization directives and simple client for auth server.

* Changed auth config.

* Revert "Upgraded to scala 2.12.3"

This reverts commit 05ee279fc88240129ef792ec2b36ae4ad5bebbca.

* Added authorize call to auth client.

* Made authorization optional.

* Removed unused authentication url.

* Added authorization rejection.

* Added logging for auth errors.

* Added authentication proxy (for bearer token authentication).

* Optimized imports and changed http method of authentication proxy.

* Changed authorization http methods.

* Added oauth2 implementation with mongo storage

* auth-server moved to harness as inner module

* cleanup docs and examples

* Added module common.

* Removed nulab lib

* Moved common oauth2 types to common, implemented authorization grant step (4.3 in spec).

* Added client's DAO

* Moved ClientId to common module

* Changed harness auth server client

* Added mongo scala driver dependencies.

* Update rest_spec.md

* POST /users as new method

* Slightly changed MongoSupport trait

* Added access token generation.

* Added auth exception handler

* Added expired tokens removal

* Added access tokens storing and checks

* Added user's creation at auth server. With roleSet templates.

* Added authorization to event routes.

* Removed old auth-server directory.

* Added security to query routes.

* merged the stats branch with status CLI

* updated install.md

* updated install.md

* Python sdk with auth (#23)

* Fixed auth server for python sdk compatibility

* Very straitforward implementation of SDK's authentication

* Disabled authentication by default at python SDK

* Added UsersClient with example call

* Added permission checks to user creation

* Added user creation example

* Refactored client auth service and fixed queries method name

* Added permissions method and example

* Added permissions management at auth server

* Harness auth server proxy supports all operations.

* Switched to client credentials support

* Switched to client credentials grant

* Moved user credentials to connection level

* Migrated to client credentials grant (oauth2 spec 4.4)

* Clients and role-sets moved to config, fixed admin example at python sdk

* auth server distribution with config file and run script (#25)

* Added auth server distribution

* Fixed certificates modifications

* Changed rolesets

* Added config variables toggling auth

* merged users branch

* Bugfix #27 (#28)

* Fixed auth-server bug, removed verbose mongo logs

* Added ENV variables to python example scripts

* Added import

* refactoring command scripts

* Added ssl support to Java SDK

* Added auth support to java sdk (#30)

* Added auth support to java sdk

* Changed client user_* env names

* Updated config and ssl support

* Fixed ssl support in python sdk

* Added harness rest env variables for ssl

* Added CA jks and updated config

* Improved config

diff --git a/rest-server/bin/harness-status b/rest-server/bin/harness-status
--- a/rest-server/bin/harness-status
+++ b/rest-server/bin/harness-status
@@ -2,14 +2,70 @@
 
 . "${HARNESS_HOME}/bin/harness-env"
 
-echo -e "${GLINE}"
-echo "HARNESS_HOME........${HARNESS_HOME}"
-echo "REST_SERVER_HOST....${REST_SERVER_HOST}"
-echo "REST_SERVER_PORT....${REST_SERVER_PORT}"
-echo "MONGO_HOST..........${MONGO_HOST}"
-echo "MONGO_PORT..........${MONGO_PORT}"
-echo "HARNESS_LOG_CONFIG..${HARNESS_LOG_CONFIG}"
-echo "HARNESS_LOG_PATH....${HARNESS_LOG_PATH}"
-echo -e "${RLINE}"
+RESOURCE_TYPE=$1
+RESOURCE_ID=$2
 
-${HARNESS_HOME}/bin/command.py status
+if [ -z "$RESOURCE_TYPE" ] ; then
+    echo -e "${CYAN}Getting Harness Server status${NC}"
+    echo -e "${GLINE}"
+    echo "HARNESS_HOME........${HARNESS_HOME}"
+    echo "REST_SERVER_HOST....${REST_SERVER_HOST}"
+    echo "REST_SERVER_PORT....${REST_SERVER_PORT}"
+    echo "MONGO_HOST..........${MONGO_HOST}"
+    echo "MONGO_PORT..........${MONGO_PORT}"
+    echo "HARNESS_LOG_CONFIG..${HARNESS_LOG_CONFIG}"
+    echo "HARNESS_LOG_PATH....${HARNESS_LOG_PATH}"
+    echo -e "${RLINE}"
+    ${HARNESS_HOME}/bin/commands.py status
+    exit 1
+fi
+
+if [ ${RESOURCE_TYPE} = "engines" ]; then
+
+    if [ -z ${RESOURCE_ID} ]; then
+        PYTHON_ARGS="status --all_engines $USER_ARGS"
+
+        echo -e "${CYAN}Run ${HARNESS_HOME}/bin/engines.py ${PYTHON_ARGS}${NC}"
+
+        ${HARNESS_HOME}/bin/engines.py ${PYTHON_ARGS}
+        exit $?
+    fi
+
+    if [ ! -z ${RESOURCE_ID} ]; then
+        PYTHON_ARGS="status -e ${RESOURCE_ID} $USER_ARGS"
+
+        echo -e "${CYAN}Run ${HARNESS_HOME}/bin/engines.py ${PYTHON_ARGS}${NC}"
+
+        ${HARNESS_HOME}/bin/engines.py ${PYTHON_ARGS}
+        exit $?
+    fi
+
+fi
+
+if [ ${RESOURCE_TYPE} = "users" ]; then
+    if [ -z ${RESOURCE_ID} ]; then
+        PYTHON_ARGS="status --all_users $USER_ARGS"
+
+        echo -e "${CYAN}Run ${HARNESS_HOME}/bin/engines.py ${PYTHON_ARGS}${NC}"
+
+        ${HARNESS_HOME}/bin/users.py ${PYTHON_ARGS}
+        exit $?
+    fi
+
+    if [ ! -z ${RESOURCE_ID} ]; then
+        PYTHON_ARGS="status --user_id ${RESOURCE_ID} $USER_ARGS"
+
+        echo -e "${CYAN}Run ${HARNESS_HOME}/bin/users.py ${PYTHON_ARGS}${NC}"
+
+        ${HARNESS_HOME}/bin/users.py ${PYTHON_ARGS}
+        exit $?
+    fi
+
+fi
+
+echo -e "   ${RED}Error in command, should be:  harness status [[ engines | engines <engine-id>]]${NC}"
+echo -e "       Prints a status message for the harness server, all engines or for the engine specified."
+echo ""
+
+
+
