fixed bug in harness-stop

diff --git a/rest-server/bin/harness-stop b/rest-server/bin/harness-stop
--- a/rest-server/bin/harness-stop
+++ b/rest-server/bin/harness-stop
@@ -3,25 +3,25 @@
 . "${HARNESS_HOME}/bin/harness-env"
 
 export PIDFILE=${HARNESS_HOME}/harness.pid
-
-killwait_pid=$1
-killwait_timeout=30
+sd_delay=60
 
 # Harness Server
 
 # wait for a pid to be killed for max time then kill -9 to really kill it
 killwait(){ # pid passed as $1
+    killwait_pid=$1
+    killwait_timeout=30
     killwait_loops=0
     killwait_sleep=0.5
-    p=`ps aux | grep "${killwait_pid}.*com.actionml.HarnessServer" | wc -l`
+    p=`ps aux | grep "${killwait_pid}.*com\.actionml\.HarnessServer" | wc -l`
 
-    #echo "Killing pid: ${killwait_pid}"
+    echo "Killing pid: ${killwait_pid}"
     # while `kill  -2 "${killwait_pid}"`; do
     while (( p == 1 )); do
         kill  -2 "${killwait_pid}"
         printf "%0.s." # print dots every half-second
         sleep ${killwait_sleep}
-        p=`ps aux | grep "${killwait_pid}.*com.actionml.HarnessServer" | wc -l`
+        p=`ps aux | grep "${killwait_pid}.*com\.actionml\.HarnessServer" | wc -l`
         (( killwait_loops = killwait_loops + 1 ))
         if (( killwait_loops > killwait_timeout )); then
             echo -e "\nTimed out, performing hard termination" # \n after dot
@@ -39,6 +39,13 @@ if [ -e ${PIDFILE} ]; then
     echo -e "${GREEN}Stopping Harness Server on pid: ${pid} ${NC}"
     #kill ${pid} # Todo: this should not use -9, find why Harness is sometimes not stopping with only kill pid
     killwait ${pid}
+    #sleep ${sd_delay}
+
+    #h=`jps -l | grep actionml | wc -l`
+    #if [[ "$h" -gt "0" ]]; then
+    #    echo -e "${RED}Error Harness failed to shutdown after ${sd_delay} seconds, there are $h instances of harness running.${NC}"
+    #    exit 1
+    #fi
 
     if [[ $? != 0 ]]; then # this is not sufficient, the command is async so the stop will return but the pid may be active
         echo -e "${RED}Unable to stop Harness from PID file. May already be stopped.${NC}"
@@ -48,10 +55,3 @@ if [ -e ${PIDFILE} ]; then
 else
     echo -e "${RED}PID file not found.${NC}"
 fi
-
-#sleep 10
-#vw=`ps aux | grep " vw$"`
-#vwnum=`ps aux | grep " vw$" | wc -l`
-#echo ${vw}
-#echo "Number of VW instances still running after harness stop: ${vwnum}"
-
