made harness and harness-auth start also handle error conditions and do foreced restarts

diff --git a/rest-server/auth-server/bin/harness-auth-start b/rest-server/auth-server/bin/harness-auth-start
--- a/rest-server/auth-server/bin/harness-auth-start
+++ b/rest-server/auth-server/bin/harness-auth-start
@@ -6,28 +6,40 @@ PIDFILE=${HARNESS_AUTH_HOME}/authserver.pid
 
 if [ ! -f "${HARNESS_AUTH_HOME}/bin/main" ]; then
     echo -e "${RED}Main file '${HARNESS_AUTH_HOME}/bin/main' not found!${NC}"
-    echo -e "${RED}The Harness Auth Server must be run after doing a distribution build${NC}"
+    echo -e "${RED}The Harness Server must be run after doing a distribution build${NC}"
     exit 1
 fi
 
-HARNESS_AUTH_CONFIG=${HARNESS_AUTH_HOME}/conf/application.conf
-HARNESS_AUTH_LOG_CONFIG=${HARNESS_AUTH_HOME}/conf/logback.xml
+export HARNESS_AUTH_CONFIG=${HARNESS_AUTH_HOME}/conf/application.conf
+export HARNESS_AUTH_LOG_CONFIG=${HARNESS_AUTH_HOME}/conf/logback.xml
 
+echo -e "${CYAN}Harness Auth Server settings${NC}"
 echo -e "${GLINE}"
-echo "HARNESS_AUTH_CONFIG..${HARNESS_AUTH_CONFIG}"
-echo "HARNESS_AUTH_LOG_CONFIG..${HARNESS_AUTH_LOG_CONFIG}"
+echo "AUTH_MONGO_HOST................${AUTH_MONGO_HOST}"
+echo "AUTH_MONGO_PORT................${AUTH_MONGO_PORT}"
+echo "HARNESS_AUTH_CONFIG............${HARNESS_AUTH_CONFIG}"
+echo "HARNESS_AUTH_LOG_CONFIG........${HARNESS_AUTH_LOG_CONFIG}"
 echo "HARNESS_AUTH_SERVER_PROTECTED..${HARNESS_AUTH_SERVER_PROTECTED:-false}"
-echo ""
-echo "Run ${HARNESS_AUTH_HOME}/bin/main"
-echo "Create pid file: ${PIDFILE}"
+echo "PIDFILE........................${PIDFILE}"
 
-if [ ! -f ${PIDFILE} ]; then
+if [[ "$1" = "-f" ]] || [[ ! -f ${PIDFILE} ]]; then
+    if [[ -f ${PIDFILE} ]] && [[ "$1" = "-f" ]]; then
+        echo -e "${CYAN}Trying to stop Harness Auth Server from existing PID file before restarting${NC}"
+        harness-auth-stop
+    fi
     exec ${HARNESS_AUTH_HOME}/bin/main \
     -Dconfig.file=${HARNESS_AUTH_CONFIG} \
     -Dlogback.configurationFile=${HARNESS_AUTH_LOG_CONFIG} \
     <&- > /dev/null 2>&1 &
     echo $! > ${PIDFILE}
+    if [[ $? == 0 ]]; then
+        echo -e "${CYAN}Started Harness Auth Server with PID: $(cat ${PIDFILE})${NC}"
+        echo -e "${GLINE}${NC}"
+    else
+        echo -e "${RED}[Error] Unable to start Harness Auth Server. Unknown reason.${NC}"
+    fi
+else
+    echo -e "${RED}There is an existing PID file, this means Harness Auth Server may be running.${NC}"
+    echo -e "${RED}Run \"harness-auth start -f\" to force a restart${NC}"
+    exit 1
 fi
-
-echo "PID.................$(cat ${PIDFILE})"
-echo -e "${RLINE}"
diff --git a/rest-server/bin/harness-start b/rest-server/bin/harness-start
--- a/rest-server/bin/harness-start
+++ b/rest-server/bin/harness-start
@@ -11,24 +11,23 @@ if [ ! -f "${HARNESS_HOME}/bin/main" ]; then
 fi
 
 
+echo -e "${CYAN}Harness Server settings${NC}"
 echo -e "${GLINE}"
-echo "REST_SERVER_HOST....${REST_SERVER_HOST}"
-echo "REST_SERVER_PORT....${REST_SERVER_PORT}"
-echo "MONGO_HOST..........${MONGO_HOST}"
-echo "MONGO_PORT..........${MONGO_PORT}"
-echo "HARNESS_LOG_CONFIG..${HARNESS_LOG_CONFIG}"
-echo "HARNESS_LOG_PATH....${HARNESS_LOG_PATH}"
-echo "HARNESS_AUTH_ENABLED....${HARNESS_AUTH_ENABLED}"
+echo "HARNESS_HOME................${HARNESS_HOME}"
+echo "REST_SERVER_HOST............${REST_SERVER_HOST}"
+echo "REST_SERVER_PORT............${REST_SERVER_PORT}"
+echo "MONGO_HOST..................${MONGO_HOST}"
+echo "MONGO_PORT..................${MONGO_PORT}"
+echo "HARNESS_LOG_CONFIG..........${HARNESS_LOG_CONFIG}"
+echo "HARNESS_LOG_PATH............${HARNESS_LOG_PATH}"
+echo "HARNESS_SSL_ENABLED.........${HARNESS_SSL_ENABLED}"
+echo "HARNESS_AUTH_ENABLED........${HARNESS_AUTH_ENABLED}"
 echo "HARNESS_KEYSTORE_PASSWORD...${HARNESS_KEYSTORE_PASSWORD}"
-echo "HARNESS_KEYSTORE_PATH...${HARNESS_KEYSTORE_PATH}"
-echo "HARNESS_SSL_ENABLED....${HARNESS_SSL_ENABLED}"
-echo ""
+echo "HARNESS_KEYSTORE_PATH.......${HARNESS_KEYSTORE_PATH}"
+echo "PIDFILE.....................${PIDFILE}"
 
-echo "Run ${HARNESS_HOME}/bin/main"
-echo "Create pid file: ${PIDFILE}"
-
-if [ ! -f ${PIDFILE} ] || [ $2 = "-f" ]; then
-    if [ $2 = "-f" ] && [ -f ${PIDFILE} ]; then
+if [[ "$1" = "-f" ]] || [[ ! -f ${PIDFILE} ]]; then
+    if [[ -f ${PIDFILE} ]] && [[ "$1" = "-f" ]]; then
         echo -e "${CYAN}Trying to stop Harness from existing PID file before restarting${NC}"
         harness-stop
     fi
@@ -41,11 +40,14 @@ if [ ! -f ${PIDFILE} ] || [ $2 = "-f" ]; then
     -Dmongo.port=${MONGO_PORT} \
     <&- > /dev/null 2>&1 &
     echo $! > ${PIDFILE}
+    if [[ $? == 0 ]]; then
+        echo -e "${CYAN}Started Harness with PID: $(cat ${PIDFILE})${NC}"
+        echo -e "${GLINE}${NC}"
+    else
+        echo -e "${RED}[Error] Unable to start Harness. Unknown reason.${NC}"
+    fi
 else
-    echo -e "${RED}There is an existing PID file, this means Harness may be running, stop it first.${NC}"
-    echo -e "${RED}If you have killed Harness, run \"harness start -f\" to force a restart${NC}"
+    echo -e "${RED}There is an existing PID file, this means Harness may be running.${NC}"
+    echo -e "${RED}Run \"harness start -f\" to force a restart${NC}"
+    exit 1
 fi
-
-
-echo "PID.................$(cat ${PIDFILE})"
-echo -e "${RLINE}"
diff --git a/rest-server/bin/harness-stop b/rest-server/bin/harness-stop
--- a/rest-server/bin/harness-stop
+++ b/rest-server/bin/harness-stop
@@ -3,11 +3,15 @@
 . "${HARNESS_HOME}/bin/harness-env"
 
 # Harness Server
-echo -e "${GREEN}Stopping Harness Server...${NC}"
+echo -e "${GREEN}Stopping Harness Server.${NC}"
 PIDFILE=${HARNESS_HOME}/eventserver.pid
 if [ -e ${PIDFILE} ]; then
     cat ${PIDFILE} | xargs kill
+    if [[ $? != 0 ]]; then
+        echo -e "${RED}Unable to stop Harness from PID file. May already be stopped.${NC}"
+        echo -e "${RED}Removing PID file.${NC}"
+    fi
     rm ${PIDFILE}
 else
-    echo -e "${RED}Pid file not found!${NC}"
+    echo -e "${RED}PID file not found.${NC}"
 fi
