merged RC2 develop branch

diff --git a/rest-server/auth-server/bin/harness-auth-stop b/rest-server/auth-server/bin/harness-auth-stop
--- a/rest-server/auth-server/bin/harness-auth-stop
+++ b/rest-server/auth-server/bin/harness-auth-stop
@@ -1,13 +1,18 @@
 #!/usr/bin/env bash
 
-. "${HARNESS_AUTH_HOME}/bin/harness-env"
+. "${HARNESS_AUTH_HOME}/bin/harness-auth-env"
 
 # Harness Server
-echo -e "${GREEN}Stopping Harness Auth Server...${NC}"
+echo -e "${GREEN}Stopping Harness Auth Server.${NC}"
 PIDFILE=${HARNESS_AUTH_HOME}/authserver.pid
+
 if [ -e ${PIDFILE} ]; then
     cat ${PIDFILE} | xargs kill
+    if [[ $? != 0 ]]; then
+        echo -e "${RED}Unable to stop Harness Auth Server from PID file. It may already be stopped.${NC}"
+        echo -e "${RED}Removing PID file.${NC}"
+    fi
     rm ${PIDFILE}
 else
-    echo -e "${RED}Pid file not found!${NC}"
+    echo -e "${RED}PID file not found.${NC}"
 fi
diff --git a/rest-server/bin/harness-start b/rest-server/bin/harness-start
--- a/rest-server/bin/harness-start
+++ b/rest-server/bin/harness-start
@@ -6,27 +6,31 @@ PIDFILE=${HARNESS_HOME}/eventserver.pid
 
 if [ ! -f "${HARNESS_HOME}/bin/main" ]; then
     echo -e "${RED}Main file '${HARNESS_HOME}/bin/main' not found!${NC}"
+    echo -e "${RED}The Harness Server must be run after doing a distribution build${NC}"
     exit 1
 fi
 
 
+echo -e "${CYAN}Harness Server settings${NC}"
 echo -e "${GLINE}"
-echo "REST_SERVER_HOST....${REST_SERVER_HOST}"
-echo "REST_SERVER_PORT....${REST_SERVER_PORT}"
-echo "MONGO_HOST..........${MONGO_HOST}"
-echo "MONGO_PORT..........${MONGO_PORT}"
-echo "HARNESS_LOG_CONFIG..${HARNESS_LOG_CONFIG}"
-echo "HARNESS_LOG_PATH....${HARNESS_LOG_PATH}"
-echo "HARNESS_AUTH_ENABLED....${HARNESS_AUTH_ENABLED}"
+echo "HARNESS_HOME................${HARNESS_HOME}"
+echo "REST_SERVER_HOST............${REST_SERVER_HOST}"
+echo "REST_SERVER_PORT............${REST_SERVER_PORT}"
+echo "MONGO_HOST..................${MONGO_HOST}"
+echo "MONGO_PORT..................${MONGO_PORT}"
+echo "HARNESS_LOG_CONFIG..........${HARNESS_LOG_CONFIG}"
+echo "HARNESS_LOG_PATH............${HARNESS_LOG_PATH}"
+echo "HARNESS_SSL_ENABLED.........${HARNESS_SSL_ENABLED}"
+echo "HARNESS_AUTH_ENABLED........${HARNESS_AUTH_ENABLED}"
 echo "HARNESS_KEYSTORE_PASSWORD...${HARNESS_KEYSTORE_PASSWORD}"
-echo "HARNESS_KEYSTORE_PATH...${HARNESS_KEYSTORE_PATH}"
-echo "HARNESS_SSL_ENABLED....${HARNESS_SSL_ENABLED}"
-echo ""
+echo "HARNESS_KEYSTORE_PATH.......${HARNESS_KEYSTORE_PATH}"
+echo "PIDFILE.....................${PIDFILE}"
 
-echo "Run ${HARNESS_HOME}/bin/main"
-echo "Create pid file: ${PIDFILE}"
-
-if [ ! -f ${PIDFILE} ]; then
+if [[ "$1" = "-f" ]] || [[ ! -f ${PIDFILE} ]]; then
+    if [[ -f ${PIDFILE} ]] && [[ "$1" = "-f" ]]; then
+        echo -e "${CYAN}Trying to stop Harness from existing PID file before restarting${NC}"
+        harness-stop
+    fi
     exec ${HARNESS_HOME}/bin/main \
     -Dlogback.configurationFile=${HARNESS_LOG_CONFIG} \
     -DHARNESS_LOG_PATH=${HARNESS_LOG_PATH} \
@@ -36,7 +40,14 @@ if [ ! -f ${PIDFILE} ]; then
     -Dmongo.port=${MONGO_PORT} \
     <&- > /dev/null 2>&1 &
     echo $! > ${PIDFILE}
+    if [[ $? == 0 ]]; then
+        echo -e "${CYAN}Started Harness with PID: $(cat ${PIDFILE})${NC}"
+        echo -e "${GLINE}${NC}"
+    else
+        echo -e "${RED}[Error] Unable to start Harness. Unknown reason.${NC}"
+    fi
+else
+    echo -e "${RED}There is an existing PID file, this means Harness may be running.${NC}"
+    echo -e "${RED}Run \"harness start -f\" to force a restart${NC}"
+    exit 1
 fi
-
-echo "PID.................$(cat ${PIDFILE})"
-echo -e "${RLINE}"
